INSERT INTO public.ref_anchor (anchor) VALUES
	 ('home'),
	 ('about'),
	 ('work');
INSERT INTO public.ref_tag (tag) VALUES
	 ('b'),
	 ('br'),
	 ('h1'),
	 ('h2'),
	 ('h3'),
	 ('input'),
	 ('p'),
	 ('textarea'),
	 ('Card'),
	 ('SkillsCloud'),
	 ('Slideshow');
INSERT INTO public.ref_techno (name) VALUES
	 ('accessibilité'),
	 ('JavaScript'),
	 ('CSS'),
	 ('GitHub'),
	 ('HTML'),
	 ('Bootstrap'),
	 ('Responsive design'),
	 ('React'),
	 ('Recharts'),
	 ('API REST'),
	 (' Modules CSS'),
	 ('JSDoc'),
	 ('React Router'),
	 ('Animations CSS'),
	 (' Sass'),
	 ('Jest'),
	 ('Testing Library'),
	 ('Redux'),
	 ('plugin npm'),
	 ('TypeScript'),
	 ('Figma'),
	 ('Supabase'),
	 ('Vercel');
