drop view if exists "public"."accounts_public";

drop view if exists "public"."project_summary";

drop view if exists "public"."skills_with_property";

drop view if exists "public"."contact_form_full";

create table "public"."contacts" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "company" text,
    "email" text not null,
    "tel" text,
    "message" text not null,
    "consent" boolean not null,
    "created_at" timestamp without time zone not null default now()
);


alter table "public"."contact_form_modal" drop column "url_api";

alter table "public"."contact_form_modal" drop column "url_form_content";

CREATE UNIQUE INDEX contacts_pkey ON public.contacts USING btree (id);

alter table "public"."contacts" add constraint "contacts_pkey" PRIMARY KEY using index "contacts_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_accounts_public()
 RETURNS SETOF jsonb
 LANGUAGE sql
 STABLE
AS $function$
	SELECT
		strip_nulls_recursively(
			jsonb_build_object(
				'id',			a.id,
				'service',		a.service,
				'icon',			a.icon,
				'onPage',		a.on_page,
				'address',		a.address
			)
		)
	FROM public.accounts a
$function$
;

CREATE OR REPLACE FUNCTION public.get_project_summary()
 RETURNS SETOF jsonb
 LANGUAGE sql
 STABLE
AS $function$
	select
		strip_nulls_recursively(
			jsonb_build_object(
				'id',			p.id::text,
				'title',		p.title,
				'description',	p.description,
				'tags',			(
					select jsonb_agg(tn)
					from (
						select rt.name as tn
						from public.project_techno pt
						join public.ref_techno rt on pt.techno_id = rt.id
						where pt.project_id = p.id
					) sub
				),
				'picture',		p.picture,
				'display',		p.display,
				'deliverables',	(
					select jsonb_agg(
						jsonb_build_object(
							'id',		pd.id::text,
							'service',	a.service,
							'icon',		a.icon,
							'address',	a.address,
							'path',		pd.path
						)
					)
					from public.project_deliverables pd
					join public.accounts a on pd.account_id = a.id
					where pd.project_id = p.id
				)
			)
		)
	from public.projects p
$function$
;

CREATE OR REPLACE FUNCTION public.get_skills_with_property()
 RETURNS SETOF jsonb
 LANGUAGE sql
 STABLE
AS $function$
	select
		strip_nulls_recursively(
			jsonb_build_object(
				'text',			s.skill,
				'value',		s.value,
				'font',			s.font,
				'fontSize',		s.font_size,
				'fontStyle',	s.font_style,
				'fontWeight',	s.font_weight
			)
		)
	from public.skills s
$function$
;

create or replace view "public"."contact_form_full" as  WITH cleaned AS (
         SELECT strip_nulls_recursively(jsonb_build_object('id', cfm.id, 'submitButtonName', cfm.submit_button_name, 'title', cfm.title, 'subtitle', cfm.subtitle, 'alertOnSubmit', cfm.alert_on_submit, 'dataFormContent', ( SELECT jsonb_agg(jsonb_build_object('id', cfi.id, 'label', cfi.label, 'tooltipContent', ( SELECT jsonb_agg(jsonb_build_object('id', (cft.id)::text, 'line', cft.line, 'lineHeight', cft.line_height)) AS jsonb_agg
                           FROM contact_form_tooltips cft
                          WHERE (cft.contact_form_input_id = cfi.id)), 'input', jsonb_build_object('id', (fi.id)::text, 'tag', rt.tag, 'type', fi.type, 'placeholder', fi.placeholder, 'pattern', fi.pattern, 'required', fi.required, 'maxLength', fi.max_length, 'minLength', fi.min_length, 'error', ( SELECT jsonb_build_object('id', (em.id)::text, 'patternMismatch', em.pattern_mismatch, 'tooLong', em.too_long, 'tooShort', em.too_short, 'valueMissing', em.value_missing) AS jsonb_build_object
                           FROM error_messages em
                          WHERE (em.form_input_id = fi.id))))) AS jsonb_agg
                   FROM (((contact_form_modal_inputs cfmi
                     JOIN contact_form_inputs cfi ON ((cfmi.contact_form_input_id = cfi.id)))
                     JOIN form_inputs fi ON ((cfi.form_input_id = fi.id)))
                     LEFT JOIN ref_tag rt ON ((fi.tag_id = rt.id)))
                  WHERE (cfmi.contact_form_modal_id = cfm.id)))) AS doc
           FROM contact_form_modal cfm
        )
 SELECT (cleaned.doc ->> 'id'::text) AS id,
    (cleaned.doc ->> 'submitButtonName'::text) AS "submitButtonName",
    (cleaned.doc ->> 'title'::text) AS title,
    (cleaned.doc ->> 'subtitle'::text) AS subtitle,
    (cleaned.doc -> 'alertOnSubmit'::text) AS "alertOnSubmit",
    (cleaned.doc -> 'dataFormContent'::text) AS "dataFormContent"
   FROM cleaned;


CREATE OR REPLACE FUNCTION public.get_showcase_with_details_and_bold()
 RETURNS SETOF jsonb
 LANGUAGE sql
 STABLE
AS $function$
	select
		public.strip_nulls_recursively(
			jsonb_build_object(
				'id', 		ss.id::text,
				'anchor',	a.anchor,
				'title',	ss.title,
				'content',	(
					select jsonb_agg(
						jsonb_build_object(
							'id',			ds.id::text,
							'tag',			t.tag,
							'wrapped',		ds.wrapped,
							'name',			ds.name,
							'content',		ds.content,
							'endpoint',	ds.url_content,
							'boldContent',	(
								select jsonb_agg(
									jsonb_build_object(
										'id',		bds.id::text,
										'tag',		bt.tag,
										'content',	bds.content
									)
								)
								from public.bold_detail_sections bds
								left join public.ref_tag bt on bds.tag_id = bt.id
								where bds.detail_section_id = ds.id
							)
						)
					) filter (where ds.id is not null)
				)
			)
		) as _
	from public.showcase_sections ss
	left join public.detail_sections ds on ss.id = ds.showcase_section_id
	left join public.ref_tag t on ds.tag_id = t.id
	left join public.ref_anchor a on ss.anchor_id = a.id
	group by ss.id, a.anchor
$function$
;

grant delete on table "public"."contacts" to "anon";

grant insert on table "public"."contacts" to "anon";

grant references on table "public"."contacts" to "anon";

grant select on table "public"."contacts" to "anon";

grant trigger on table "public"."contacts" to "anon";

grant truncate on table "public"."contacts" to "anon";

grant update on table "public"."contacts" to "anon";

grant delete on table "public"."contacts" to "authenticated";

grant insert on table "public"."contacts" to "authenticated";

grant references on table "public"."contacts" to "authenticated";

grant select on table "public"."contacts" to "authenticated";

grant trigger on table "public"."contacts" to "authenticated";

grant truncate on table "public"."contacts" to "authenticated";

grant update on table "public"."contacts" to "authenticated";

grant delete on table "public"."contacts" to "service_role";

grant insert on table "public"."contacts" to "service_role";

grant references on table "public"."contacts" to "service_role";

grant select on table "public"."contacts" to "service_role";

grant trigger on table "public"."contacts" to "service_role";

grant truncate on table "public"."contacts" to "service_role";

grant update on table "public"."contacts" to "service_role";



