import React, { FormEvent, memo, useCallback, useEffect, useRef } from 'react';

import { useFetchData } from '@/hooks/useFetchData';
import { createError } from '@/modules/Error/utils/errorHandling';
import { handleFetchError } from '@/utils/fetchDataHelpers';
import { getFetchUrlOrUrls } from '@/utils/urlHelpers';
import { useErrorHandler } from '@modules/Error/hooks/useErrorHandler';

import { FormContent } from './Components/FormContent';
import style from './style.module.css';
import { useContactFormFieldsPropSelector } from '../../hooks/useContactFormFieldsPropSelector';
import type { FormProps } from '../../types';

/**
 * The Form component integrates the FormContent component and handles the connection with the API.
 * Form component memoized with 'React.memo' to optimize performance. The component will only
 * re-render if the props change.
 *
 * @component Form
 * @param {FormProps} props - The properties for the Form component.
 * @property {string} idForm - The form identifier in HTML.
 * @property {ContactFormInput[]} dataFormContent - Data on elements embedded in the FormContent component.
 * @property {SetStateBoolean} setShowAlert - A function to toggle the open/close state of the alert modal.
 * @property {SetStateBoolean} onRenderComplete - Function to toggle the flag that tracks whether the
 * FormContent component is rendered.
 * @property {string} [csrfToken] - The token is generated by the server and must be included in state-changing
 * requests to verify that the request originates from a trusted client.
 *
 * @returns {React.JSX.Element}
 *
 * @al-dev93
 */
function MemoizedForm({
  idForm,
  dataFormContent,
  setShowAlert,
  onRenderComplete,
  csrfToken = '',
}: FormProps): React.JSX.Element | null {
  const handleError = useErrorHandler();
  const websiteRef = useRef<HTMLInputElement>(null);
  // Extracts validated values from contact form input elements
  const validValues = useContactFormFieldsPropSelector('inputValue', true);
  // Prepare for submitting form data via POST
  const { refetch, fetchError } = useFetchData({
    endpoint: null,
    initialOptions: {},
    shouldRefetch: true,
  });

  useEffect(() => {
    if (fetchError) {
      // eslint-disable-next-line no-void
      void handleFetchError('Form', fetchError, handleError);
    }
  }, [fetchError, handleError]);

  /**
   * Refetches the form data with the provided arguments.
   *
   * @function createContactEntry
   * @param {Object} payload - An object containing the arguments to be passed to the fetch function.
   * @returns {void}
   */
  const createContactEntry = useCallback(
    async (payload: { [x: string]: unknown }): Promise<void> => {
      const endpoint = import.meta.env.VITE_API_FORM_RESPONSES_ENDPOINT;
      const initialOptions = { method: 'POST' };
      const { apiEndpoint, apiOptions } = getFetchUrlOrUrls({ endpoint, initialOptions, edgeFunction: true });
      let isFetched = false;

      apiOptions.body = payload ? JSON.stringify(payload) : null;
      if (apiEndpoint && typeof apiEndpoint === 'string') {
        try {
          await refetch(apiEndpoint, apiOptions);
          isFetched = true;
        } catch (err) {
          isFetched = false;
          await handleError(
            createError(2104, 'Form submission failed : error during POST request execution.', {
              originalError: err,
              component: 'Form',
              operation: 'handleFormSubmission',
              category: 'Validation',
              url: window.location.href,
            }),
          );
        } finally {
          setShowAlert(isFetched);
        }
      }
    },
    [handleError, refetch, setShowAlert],
  );

  /**
   * Handles the form submission process. Validates form inputs and triggers an API request
   * if the form values are valid.
   * Add honeypot and token content for CSRF protection.
   *
   * @function handleFormSubmission
   * @param {FormEvent<HTMLFormElement>} event - The form submit event.
   * @returns {void}
   */
  const handleFormSubmission = useCallback(
    async (event: FormEvent<HTMLFormElement>): Promise<void> => {
      event.preventDefault();
      event.stopPropagation();
      if (validValues) {
        await createContactEntry({ ...validValues, website: websiteRef.current?.value, csrfToken });
      }
    },
    [createContactEntry, csrfToken, validValues],
  );

  return (
    <form
      className={style.contactForm}
      // aria-label='formulaire de contact'
      action=''
      id={idForm}
      method='dialog'
      onSubmit={handleFormSubmission}
      noValidate
    >
      <input type='hidden' name='_csrf' value={csrfToken} />
      <FormContent dataFormContent={dataFormContent} onRenderComplete={onRenderComplete} />
      <div className={style.hidingWrap}>
        <input type='text' name='website' aria-hidden='true' tabIndex={-1} autoComplete='off' ref={websiteRef} />
      </div>
    </form>
  );
}

export const Form = memo(MemoizedForm);
